<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  <Actions category="Tools">
    <text>Composition Helper</text>

    <Action name="pykrita_compositionhelper">
      <icon></icon>
      <text>Composition Helper</text>
      <whatsThis></whatsThis>
      <toolTip></toolTip>
      <iconText></iconText>
      <activationFlags>0</activationFlags>
      <activationConditions>0</activationConditions>
      <shortcut></shortcut>
      <isCheckable>false</isCheckable>
      <statusTip></statusTip>
    </Action>
  </Actions>
</ActionCollection>
